### ISSUE TITLE
Missing wl_touch support

### ISSUE THREAD

**Issue by cptn-cosmo** [Supreeeme/xwayland-satellite#1]
thanks for your awesome work!

i just wanted to try it, but i am getting this error message:

```
[cosmo@pocketarch xwayland-satellite]$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.68s
     Running `target/debug/xwayland-satellite`
 2024-04-29T10:23:51.692Z INFO  xwayland_satellite > Connected to Xwayland on :0
 2024-04-29T10:23:51.693Z WARN  xwayland_satellite::server::dispatch > unhandled seat request: GetTouch { id: New { id: WlTouch { id: ObjectId(wl_touch@20[0], 30), version: 8, data: Some(Any { .. }), handle: WeakHandle { handle: WeakInnerHandle[rs] { .. } } } } }
thread 'main' panicked at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.3.3/src/rs/server_impl/common_poll.rs:259:37:
Callback creating object wl_touch@20[0] did not provide any object data.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by cptn-cosmo** [comment]
with the backtrace:

`[cosmo@pocketarch xwayland-satellite]$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `target/debug/xwayland-satellite`
 2024-04-29T10:26:21.510Z INFO  xwayland_satellite > Connected to Xwayland on :0
 2024-04-29T10:26:21.511Z WARN  xwayland_satellite::server::dispatch > unhandled seat request: GetTouch { id: New { id: WlTouch { id: ObjectId(wl_touch@20[0], 30), version: 8, data: Some(Any { .. }), handle: WeakHandle { handle: WeakInnerHandle[rs] { .. } } } } }
thread 'main' panicked at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.3.3/src/rs/server_impl/common_poll.rs:259:37:
Callback creating object wl_touch@20[0] did not provide any object data.
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: wayland_backend::rs::server_impl::common_poll::InnerBackend<D>::dispatch_events_for
             at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.3.3/src/rs/server_impl/common_poll.rs:259:37
   3: wayland_backend::rs::server_impl::common_poll::InnerBackend<D>::dispatch_all_clients
             at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.3.3/src/rs/server_impl/common_poll.rs:98:36
   4: wayland_backend::rs::server::Backend<D>::dispatch_all_clients
             at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.3.3/src/rs/../server_api.rs:575:9
   5: wayland_server::display::Display<State>::dispatch_clients
             at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-server-0.31.1/src/display.rs:59:9
   6: xwayland_satellite::main
             at ./satellite/src/lib.rs:180:9
   7: xwayland_satellite::main
             at ./satellite/src/main.rs:6:5
   8: core::ops::function::FnOnce::call_once
             at /usr/src/debug/rust/rustc-1.77.2-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

**Comment by cptn-cosmo** [comment]
Managed to et a full backtrace:

```
[cosmo@pocketarch xwayland-satellite]$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/xwayland-satellite`
 2024-04-29T12:13:37.305Z INFO  xwayland_satellite > Connected to Xwayland on :0
 2024-04-29T12:13:37.307Z WARN  xwayland_satellite::server::dispatch > unhandled seat request: GetTouch { id: New { id: WlTouch { id: ObjectId(wl_touch@20[0], 31), version: 8, data: Some(Any { .. }), handle: WeakHandle { handle: WeakInnerHandle[rs] { .. } } } } }
thread 'main' panicked at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.3.3/src/rs/server_impl/common_poll.rs:259:37:
Callback creating object wl_touch@20[0] did not provide any object data.
stack backtrace:
   0:     0x5648866e7906 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2fe490803af88cd5
   1:     0x56488670bf50 - core::fmt::write::h0e806f9ceb53dc01
   2:     0x5648866e501d - std::io::Write::write_fmt::hc993ca4907c5591c
   3:     0x5648866e76e4 - std::sys_common::backtrace::print::h7188c066e4378df6
   4:     0x5648866e9147 - std::panicking::default_hook::{{closure}}::hdc0fc6164adc38ae
   5:     0x5648866e8ea9 - std::panicking::default_hook::h42848e1a5516cbc3
   6:     0x5648866e95d8 - std::panicking::rust_panic_with_hook::h37f14317b32091f5
   7:     0x5648866e94b2 - std::panicking::begin_panic_handler::{{closure}}::h8a1c6b82df46520d
   8:     0x5648866e7e06 - std::sys_common::backtrace::__rust_end_short_backtrace::hc4ef5a9b6f477b45
   9:     0x5648866e9204 - rust_begin_unwind
  10:     0x5648861ffde5 - core::panicking::panic_fmt::hacac095bf637f1ac
  11:     0x5648862aa6ed - wayland_backend::rs::server_impl::common_poll::InnerBackend<D>::dispatch_events_for::hb03309428b340f93
                               at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.3.3/src/rs/server_impl/common_poll.rs:259:37
  12:     0x5648862ab834 - wayland_backend::rs::server_impl::common_poll::InnerBackend<D>::dispatch_all_clients::h4733b2a307c4b124
                               at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.3.3/src/rs/server_impl/common_poll.rs:98:36
  13:     0x56488623b20b - wayland_backend::rs::server::Backend<D>::dispatch_all_clients::h24db53cc1f96c5c4
                               at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-backend-0.3.3/src/rs/../server_api.rs:575:9
  14:     0x5648862551bb - wayland_server::display::Display<State>::dispatch_clients::h19b9bd23758df080
                               at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wayland-server-0.31.1/src/display.rs:59:9
  15:     0x564886202a9c - xwayland_satellite::main::h207ab354a9272d20
                               at /home/cosmo/git/xwayland-satellite/satellite/src/lib.rs:180:9
  16:     0x56488620095e - xwayland_satellite::main::ha8239706256ff7e5
                               at /home/cosmo/git/xwayland-satellite/satellite/src/main.rs:6:5
  17:     0x56488620086b - core::ops::function::FnOnce::call_once::he30f07b4fc4898e3
                               at /usr/src/debug/rust/rustc-1.77.2-src/library/core/src/ops/function.rs:250:5
  18:     0x56488620076e - std::sys_common::backtrace::__rust_begin_short_backtrace::h5e40fe4424ce3a8c
                               at /usr/src/debug/rust/rustc-1.77.2-src/library/std/src/sys_common/backtrace.rs:155:18
  19:     0x5648862007e1 - std::rt::lang_start::{{closure}}::hc61489daa75d28a8
                               at /usr/src/debug/rust/rustc-1.77.2-src/library/std/src/rt.rs:166:18
  20:     0x5648866e0361 - std::rt::lang_start_internal::he5e87cd982b6a812
  21:     0x5648862007ba - std::rt::lang_start::hfdda680f520fae0d
                               at /usr/src/debug/rust/rustc-1.77.2-src/library/std/src/rt.rs:165:17
  22:     0x56488620099e - main
  23:     0x7fd689d5dcd0 - <unknown>
  24:     0x7fd689d5dd8a - __libc_start_main
  25:     0x564886200685 - _start
  26:                0x0 - <unknown>
```

**Comment by Supreeeme** [comment]
Ah, looks like I forgot to support touch devices. Will fix later today.
