### ISSUE TITLE
Crash in IntelliJ IDEA

### ISSUE THREAD

**Issue by YaLTeR** [Supreeeme/xwayland-satellite#16]
```
thread 'main' panicked at src/xstate.rs:40:65:
called `Result::unwrap()` on an `Err` value: Protocol(X(Window(ValueError { response_type: 0, error_code: 3, sequence: 2099, bad_value: 46137382, minor_opcode: 0, major_opcode: 20, pad: 1 }), Some("x::GetProperty")))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: unwrap<xcb::xproto::GetPropertyReply, xcb::base::Error>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
   4: resolve<xwayland_satellite::xstate::{impl#3}::get_wm_hints::{closure_env#0}>
             at ./src/xstate.rs:40:21
   5: handle_property_change
             at ./src/xstate.rs:523:29
   6: handle_events
             at ./src/xstate.rs:260:21
   7: main<xwayland_satellite::RealData>
             at ./src/lib.rs:156:13
   8: main
             at ./src/main.rs:6:5
```

**Comment by YaLTeR** [comment]
Tried again and it didn't crash. When it did, I also had Steam open.

**Comment by YaLTeR** [comment]
Got the same crash with just IDEA open while messing around with the right click menu and its submenus.
