### ISSUE TITLE
not building on fresh install

### ISSUE THREAD

**Issue by cptn-cosmo** [Supreeeme/xwayland-satellite#2]
Hi,I also have another device with a fresh archlinux installation and i wanted to try building xwayland-satellite there, but i got this error:

```
cosmo@xpsarch ~/g/xwayland-satellite (main) [127]> cargo build
   Compiling memchr v2.7.2
   Compiling proc-macro2 v1.0.81
   Compiling cfg-if v1.0.0
   Compiling unicode-ident v1.0.12
   Compiling libloading v0.8.3
   Compiling bitflags v2.5.0
   Compiling log v0.4.21
   Compiling glob v0.3.1
   Compiling pkg-config v0.3.30
   Compiling quote v1.0.36
   Compiling libc v0.2.153
   Compiling clang-sys v1.7.0
   Compiling wayland-sys v0.31.1
   Compiling rustix v0.38.34
   Compiling cc v1.0.95
   Compiling dlib v0.5.2
   Compiling regex-syntax v0.8.3
   Compiling linux-raw-sys v0.4.13
   Compiling minimal-lexical v0.2.1
   Compiling wayland-backend v0.3.3
   Compiling syn v1.0.109
   Compiling nom v7.1.3
   Compiling regex-automata v0.4.6
   Compiling aho-corasick v1.1.3
   Compiling quick-xml v0.31.0
   Compiling downcast-rs v1.2.1
   Compiling bindgen v0.64.0
   Compiling scoped-tls v1.0.1
   Compiling bitflags v1.3.2
   Compiling io-lifetimes v2.0.3
   Compiling either v1.11.0
   Compiling home v0.5.9
   Compiling smallvec v1.13.2
   Compiling which v4.4.2
   Compiling wayland-scanner v0.31.1
   Compiling regex v1.10.4
   Compiling cexpr v0.6.0
   Compiling lazycell v1.3.0
   Compiling peeking_take_while v0.1.2
   Compiling rustc-hash v1.1.0
   Compiling lazy_static v1.4.0
   Compiling shlex v1.3.0
   Compiling quick-xml v0.30.0
   Compiling xcb v1.4.0
   Compiling wayland-server v0.31.1
   Compiling wayland-client v0.31.2
   Compiling utf8parse v0.2.1
   Compiling humantime v2.1.0
   Compiling version_check v0.9.4
   Compiling anstyle-parse v0.2.3
   Compiling slotmap v1.0.7
   Compiling is-terminal v0.4.12
   Compiling termcolor v1.4.1
   Compiling colorchoice v1.0.0
   Compiling paste v1.0.14
   Compiling anstyle v1.0.6
   Compiling anstyle-query v1.0.2
   Compiling signal-hook v0.3.17
   Compiling anstream v0.6.13
   Compiling wayland-protocols v0.31.2
   Compiling wl_drm v0.1.0 (/home/cosmo/git/xwayland-satellite/wl_drm)
   Compiling env_logger v0.10.2
   Compiling env_filter v0.1.0
   Compiling signal-hook-registry v1.4.2
   Compiling xcb-util-cursor-sys v0.1.3
   Compiling env_logger v0.11.3
error: failed to run custom build command for `xcb-util-cursor-sys v0.1.3`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/cosmo/git/xwayland-satellite/target/debug/build/xcb-util-cursor-sys-76327e711a98512f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=xcb-cursor
  cargo:rerun-if-changed=wrapper.h

  --- stderr
  thread 'main' panicked at /home/cosmo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.64.0/./lib.rs:2393:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  stack backtrace:
     0:     0x5b232cdeb706 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2fe490803af88cd5
     1:     0x5b232ce14f60 - core::fmt::write::h0e806f9ceb53dc01
     2:     0x5b232cde8b7d - std::io::Write::write_fmt::hc993ca4907c5591c
     3:     0x5b232cdeb4e4 - std::sys_common::backtrace::print::h7188c066e4378df6
     4:     0x5b232cdecc07 - std::panicking::default_hook::{{closure}}::hdc0fc6164adc38ae
     5:     0x5b232cdec969 - std::panicking::default_hook::h42848e1a5516cbc3
     6:     0x5b232cded098 - std::panicking::rust_panic_with_hook::h37f14317b32091f5
     7:     0x5b232cdecf72 - std::panicking::begin_panic_handler::{{closure}}::h8a1c6b82df46520d
     8:     0x5b232cdebc06 - std::sys_common::backtrace::__rust_end_short_backtrace::hc4ef5a9b6f477b45
     9:     0x5b232cdeccc4 - rust_begin_unwind
    10:     0x5b232c88d4d5 - core::panicking::panic_fmt::hacac095bf637f1ac
    11:     0x5b232c88dab3 - core::result::unwrap_failed::h51a1fc544636e6d9
    12:     0x5b232c9ef0b3 - core::result::Result<T,E>::expect::h9ede8521dbdd816a
    13:     0x5b232c93c0ed - core::ops::function::FnOnce::call_once::hdba635a40cf5b713
    14:     0x5b232c9003fb - lazy_static::lazy::Lazy<T>::get::{{closure}}::h9310905fddc76a41
    15:     0x5b232c9b3f25 - std::sync::once::Once::call_once::{{closure}}::h2a8b96dfffc75d05
    16:     0x5b232c948dbf - std::sys_common::once::futex::Once::call::h2866ee6e5dc009bb
    17:     0x5b232c9b3def - std::sync::once::Once::call_once::h93c0818d38148332
    18:     0x5b232c9b2bc5 - <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref::he2854895ca536c0c
    19:     0x5b232c9ab3bb - bindgen::ensure_libclang_is_loaded::h8d84cbcbb96cf2bf
    20:     0x5b232c9abe75 - bindgen::Bindings::generate::hf7b9c4cad6769551
    21:     0x5b232c9a8f78 - bindgen::Builder::generate::hf03cbb40f0baa40e
    22:     0x5b232c89097c - build_script_build::main::h28e4a8863fe92ec2
    23:     0x5b232c88e903 - core::ops::function::FnOnce::call_once::hcb1c38dc78d5b134
    24:     0x5b232c88de96 - std::sys_common::backtrace::__rust_begin_short_backtrace::h46178eb7a6010f8e
    25:     0x5b232c88e599 - std::rt::lang_start::{{closure}}::hec05f6a907377d65
    26:     0x5b232cde3fd1 - std::rt::lang_start_internal::he5e87cd982b6a812
    27:     0x5b232c88e577 - std::rt::lang_start::h61c95352bdca05e6
    28:     0x5b232c890c05 - main
    29:     0x79abdc666cd0 - <unknown>
    30:     0x79abdc666d8a - __libc_start_main
    31:     0x5b232c88ddb5 - _start
    32:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
```

**Comment by Supreeeme** [comment]
You will need to install `xcb-util-cursor`. I'll have to figure out if there are any other dependencies as well and add them to the readme, but the build should succeed after installing that.

**Comment by cptn-cosmo** [comment]
thanks, that seemed to have worked, though i also had to install clang :D

**Comment by sommerper** [comment]
This is still failing for me

```
xwayland-satellite on  main [!] is 📦 v0.4.0 via 🦀 v1.77.0
❯ cargo build
   Compiling xcb-util-cursor-sys v0.1.4
error: failed to run custom build command for `xcb-util-cursor-sys v0.1.4`

Caused by:
  process didn't exit successfully: `/home/xxx/development/github/xwayland-satellite/target/debug/build/xcb-util-cursor-sys-a8d3caf9c5bb908f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=xcb-cursor
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-env-changed=XCB_CURSOR_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=XCB_CURSOR_STATIC
  cargo:rerun-if-env-changed=XCB_CURSOR_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xcb-util-cursor-sys-0.1.4/build.rs:8:10:
  Error using pkg-config to find xcb-cursor library:
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags xcb-cursor

  The system library `xcb-cursor` required by crate `xcb-util-cursor-sys` was not found.
  The file `xcb-cursor.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `xcb-cursor.pc`.

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
