### ISSUE TITLE
Crash when starting JetBrains Toolbox

### ISSUE THREAD

**Issue by YaLTeR** [Supreeeme/xwayland-satellite#20]
Different line from the other one.
```
thread 'main' panicked at src/xstate.rs:285:26:
called `Result::unwrap()` on an `Err` value: X(Window(ValueError { response_type: 0, error_code: 3, sequence: 47, bad_value: 6291459, minor_opcode: 0, major_opcode: 12, pad: 1 }), Some("x::ConfigureWindow"))
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: unwrap<(), xcb::error::ProtocolError>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
   4: handle_events
             at ./src/xstate.rs:280:21
   5: main<xwayland_satellite::RealData>
             at ./src/lib.rs:156:13
   6: main
             at ./src/main.rs:6:5
```

**Comment by Supreeeme** [comment]
Could you get a log too? (Run with RUST_LOG=debug)

**Comment by YaLTeR** [comment]
```
 2024-05-23T04:45:24.611Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 46, parent: Window { res_id: 1000 }, window: Window { res_id: 6291457 }, x: 10, y: 10, width: 10, height: 10, border_width: 0, override_redirect: false, pad: 1 }
 2024-05-23T04:45:24.772Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 46, parent: Window { res_id: 1000 }, window: Window { res_id: 6291459 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, override_redirect: false, pad: 1 }
 2024-05-23T04:45:24.785Z DEBUG xwayland_satellite::xstate           > Window { res_id: 6291459 } request: WIDTH | HEIGHT
thread 'main' panicked at src/xstate.rs:285:26:
called `Result::unwrap()` on an `Err` value: X(Window(ValueError { response_type: 0, error_code: 3, sequence: 47, bad_value: 6291459, minor_opcode: 0, major_opcode: 12, pad: 1 }), Some("x::ConfigureWindow"))
```

**Comment by YaLTeR** [comment]
Seems fixed now.
