### ISSUE TITLE
Android Studio Canary crashing on `Result::unwrap()`

### ISSUE THREAD

**Issue by Sir-Photch** [Supreeeme/xwayland-satellite#24]
Hi,

I'm having issues with Android Studio when running via xwayland-satellite.
It crashes relatively consistently, but I have not yet observed a pattern for reproducing. Is this output of help to you?

```
Mai 26 12:48:59 arpc systemd[2870]: Started xwayland-satellite.service.
Mai 26 12:48:59 arpc xwayland-satellite[44292]:  2024-05-26T10:48:59.894Z INFO  xwayland_satellite > Connected to Xwayland on :0
Mai 26 12:48:59 arpc xwayland-satellite[44292]:  2024-05-26T10:48:59.909Z INFO  xwayland_process   > The XKEYBOARD keymap compiler (xkbcomp) reports:
Mai 26 12:48:59 arpc xwayland-satellite[44292]:  2024-05-26T10:48:59.909Z INFO  xwayland_process   > > Warning:          Unsupported maximum keycode 708, clipping.
Mai 26 12:48:59 arpc xwayland-satellite[44292]:  2024-05-26T10:48:59.909Z INFO  xwayland_process   > >                   X11 cannot support keycodes above 255.
Mai 26 12:48:59 arpc xwayland-satellite[44292]:  2024-05-26T10:48:59.909Z INFO  xwayland_process   > > Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
Mai 26 12:48:59 arpc xwayland-satellite[44292]:  2024-05-26T10:48:59.909Z INFO  xwayland_process   > > Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
Mai 26 12:48:59 arpc xwayland-satellite[44292]:  2024-05-26T10:48:59.909Z INFO  xwayland_process   > Errors from xkbcomp are not fatal to the X server
Mai 26 12:49:13 arpc xwayland-satellite[44292]:  2024-05-26T10:49:13.376Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 269 }
Mai 26 12:49:13 arpc xwayland-satellite[44292]:  2024-05-26T10:49:13.392Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:49:13 arpc xwayland-satellite[44292]:  2024-05-26T10:49:13.411Z WARN  xwayland_satellite::xstate           > unrecognized message: Atom { res_id: 269 }
Mai 26 12:49:13 arpc xwayland-satellite[44292]:  2024-05-26T10:49:13.412Z WARN  xwayland_satellite::xstate           > unrecognized message: Atom { res_id: 269 }
Mai 26 12:49:13 arpc xwayland-satellite[44292]:  2024-05-26T10:49:13.647Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:49:13 arpc xwayland-satellite[44292]:  2024-05-26T10:49:13.671Z WARN  xwayland_satellite::xstate           > unrecognized message: Atom { res_id: 269 }
Mai 26 12:49:13 arpc xwayland-satellite[44292]:  2024-05-26T10:49:13.671Z WARN  xwayland_satellite::xstate           > unrecognized message: Atom { res_id: 269 }
Mai 26 12:49:13 arpc xwayland-satellite[44292]:  2024-05-26T10:49:13.689Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:49:18 arpc xwayland-satellite[44292]:  2024-05-26T10:49:18.823Z WARN  xwayland_satellite::xstate           > unrecognized message: Atom { res_id: 269 }
Mai 26 12:49:18 arpc xwayland-satellite[44292]:  2024-05-26T10:49:18.873Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:51:42 arpc xwayland-satellite[44292]:  2024-05-26T10:51:42.080Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:51:46 arpc xwayland-satellite[44292]:  2024-05-26T10:51:46.552Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:51:46 arpc xwayland-satellite[44292]:  2024-05-26T10:51:46.588Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:51:47 arpc xwayland-satellite[44292]:  2024-05-26T10:51:47.245Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:51:51 arpc xwayland-satellite[44292]:  2024-05-26T10:51:51.185Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:51:56 arpc xwayland-satellite[44292]:  2024-05-26T10:51:56.558Z WARN  xwayland_satellite::server::dispatch > unhandled surface request: SetInputRegion { region: None }
Mai 26 12:51:57 arpc xwayland-satellite[44292]: thread 'main' panicked at src/xstate.rs:40:65:
Mai 26 12:51:57 arpc xwayland-satellite[44292]: called `Result::unwrap()` on an `Err` value: Protocol(X(Window(ValueError { response_type: 0, error_code: 3, sequence: 368, bad_value: 4195208, minor_opcode: 0, major_opcode: 20, pad: 1 }), Some("x::GetProperty")))
Mai 26 12:51:57 arpc xwayland-satellite[44292]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Mai 26 12:51:57 arpc xwayland-satellite[44292]:  2024-05-26T10:51:57.028Z INFO  xwayland_process                     > (EE) failed to read Wayland events: Connection reset by peer
Mai 26 12:51:57 arpc systemd[2870]: xwayland-satellite.service: Main process exited, code=exited, status=101/n/a
Mai 26 12:51:57 arpc systemd[2870]: xwayland-satellite.service: Failed with result 'exit-code'.
```

Let me know if you need to know anything else.

**Comment by Sir-Photch** [comment]
Works fine when built on [02bee5a](https://github.com/Supreeeme/xwayland-satellite/commit/02bee5aea7d4e95abad5c6792f6caab1190a1e68), apparently

**Comment by Sir-Photch** [comment]
Okay, unfortunately, I still have this crash:

```
 2024-05-26T12:34:47.106Z INFO  xwayland_satellite > Connected to Xwayland on :0
 2024-05-26T12:34:47.119Z INFO  xwayland_process   > The XKEYBOARD keymap compiler (xkbcomp) reports:
 2024-05-26T12:34:47.119Z INFO  xwayland_process   > > Warning:          Unsupported maximum keycode 708, clipping.
 2024-05-26T12:34:47.119Z INFO  xwayland_process   > >                   X11 cannot support keycodes above 255.
 2024-05-26T12:34:47.120Z INFO  xwayland_process   > > Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
 2024-05-26T12:34:47.120Z INFO  xwayland_process   > > Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
 2024-05-26T12:34:47.120Z INFO  xwayland_process   > Errors from xkbcomp are not fatal to the X server
 2024-05-26T12:37:41.001Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 270 }
 2024-05-26T12:37:41.027Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 270 }
 2024-05-26T12:37:41.027Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 270 }
 2024-05-26T12:37:41.075Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 270 }
 2024-05-26T12:37:41.075Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 270 }
 2024-05-26T12:37:44.724Z WARN  xwayland 2024-05-26T13:16:57.906Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 270 }
ignoring non newvalue for property Atom { res_id: 331 }
ignoring non newvalue for property Atom { res_id: 331 }
 2024-05-26T13:42:57.946Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:47:41.579Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
ignoring non newvalue for property Atom { res_id: 331 }
 2024-05-26T13:50:47.356Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:50:56.188Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:51:06.946Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:51:18.459Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:53:47.775Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:54:46.296Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:58:03.119Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:58:40.822Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:58:42.969Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:58:46.644Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:58:48.377Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:58:51.662Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T13:59:36.675Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T14:06:35.040Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T14:08:33.720Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T14:09:04.740Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T14:09:40.008Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T14:10:53.786Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T14:11:14.145Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
 2024-05-26T14:11:24.777Z WARN  xwayland_satellite::xstate > unrecognized message: Atom { res_id: 250 }
thread 'main' panicked at src/xstate.rs:763:10:
called `Result::unwrap()` on an `Err` value: X(Window(ValueError { response_type: 0, error_code: 3, sequence: 21910, bad_value: 4234945, minor_opcode: 0, major_opcode: 12, pad: 1 }), Some("x::ConfigureWindow"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 2024-05-26T14:12:27.377Z INFO  xwayland_process           > (EE) failed to write to Xwayland fd: Broken pipe
```

but it worked for like 90 minutes straight, which is nice

**Comment by Supreeeme** [comment]
Hopefully I caught all of these, feel free to reopen if you still see this
