### ISSUE TITLE
Implement force scaling to 1

### ISSUE THREAD

**Issue by frigaut** [Supreeeme/xwayland-satellite#28]
Hi there - I am using xwayland-satellite with the niri compositor, for the occasional X app.
Now that niri has implemented fractional scaling (I am using 1.5), the X windows are, of course, blurry. That's a known limitation. 
hyprland has an interesting twist on their implementation of xwayland: they offer a force_zero_scaling option, and when this is set, xwayland is not scaling its windows. 
IMO, that is convenient, as I can always fudge the display DPI to get things legible, and they appear crisp. 

Would it be possible to implement something like this in xwl-s? Thanks.

**Comment by YaLTeR** [comment]
Maybe something like, tell Xwayland that the scale is 1, then use fractional-scale + viewporter to draw it at physical 1x on the host?

**Comment by zetaPRIME** [comment]
Being able to use this to essentially bodge the functionality into, say, swayfx would also be pretty great.

**Comment by Titaniumtown** [comment]
+1 I am trying to get steam working on my framework 13, it is really an eyesore.

**Comment by merrkry** [comment]
Hope [this xwayland MR](https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/733) helps. (Requires support from compositor side, e.g. [in wlroots](https://gitlab.freedesktop.org/lilydjwg/wlroots/-/commit/6c5ffcd1fee9e44780a6a8792f74ecfbe24a1ca7))

**Comment by Supreeeme** [comment]
There is now a branch, `force_unscaled` which always renders with the native resolution regardless of the scale. Any testing and feedback is appreciated. All of the text will be tiny but DPI and whatnot can be adjusted like you would on X11 (`GDK_SCALE`, `Xft.dpi`, etc). 

Before merging it into main I want to find out if:
1. Satellite can automatically make these DPI/scale adjustments
2. If auto DPI adjustments can be made, how should mixed DPIs be handled?

**Comment by margaretjoanmiller** [comment]
Testing it now, seems to be working fine but the bottoms of some windows are not interactive (in krita on niri)

**Comment by nicolas-yangli** [comment]
> Testing it now, seems to be working fine but the bottoms of some windows are not interactive (in krita on niri)

I have the same problem. I uses 150% fractional scale on niri. When I click the bottom part of a window, the coordinate is offset to some upper point.

**Comment by Supreeeme** [comment]
Ah yes, I forgot about fractional scale.

**Comment by meck** [comment]
I'm also seeing good results with 2x, i'm using xsettingsd to load the following (nix config) but note what i did to get the scaling to match, the Gdk options removes the need for `GTK_SCALE` envars:

```
  services.xsettingsd = {
    enable = true;
    settings = with flarn.gui.scale; {
      # Wayland dosen't seem to use the real
      # dpi but (scaleFactor * 96), so do
      # the same to match
      "Xft/DPI" = scaleFactor * 96 * 1024;
      "Gdk/WindowScalingFactor" = scaleFactor;
      "Gdk/UnscaledDPI" = 96 / 1024;
    };
  };
```

**Comment by Supreeeme** [comment]
I just pushed fixes for fractional scale, and I have determined to not have satellite do any auto dpi adjustments for now, because it is simply Too Hard. If I can get some people to confirm fractional scale looks good I'll merge this stuff into main.

**Comment by luleyleo** [comment]
Works great for me with a scale of 1.25 now :)

**Comment by merrkry** [comment]
Works perfect for me on Niri with 150%. This is fantastic!

**Comment by prepor** [comment]
I'm switching to linux and choosing wm/compositor. I love niri, but without x11 apps it's not really an option. I installed hyprland but when found this issue and branch. It works perfectly, thank you! It saved niri for me!

**Comment by luleyleo** [comment]
When running TeamSpeak 6 on the scaling branch, I get the following error:
```
Protocol error 0 on object wp_viewport@32: negative or zero values in width or height

thread 'main' panicked at src/server/mod.rs:1067:14:
Failed flushing clientside events: Protocol(ProtocolError { code: 0, object_id: 32, object_interface: "wp_viewport", message: "negative or zero values in width or height" })
stack backtrace:
   0:     0x5628a4f81830 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h935e271cc5fb90ba
   1:     0x5628a4fa7873 - core::fmt::write::he4ddb9182edc60d6
   2:     0x5628a4f7e743 - std::io::Write::write_fmt::hb836ec59165d98b5
   3:     0x5628a4f81682 - std::sys::backtrace::BacktraceLock::print::h7920c6a0f5f13d53
   4:     0x5628a4f828a4 - std::panicking::default_hook::{{closure}}::hcae04ba448f5a90b
   5:     0x5628a4f82714 - std::panicking::default_hook::h82731dcf856564a7
   6:     0x5628a4f83242 - std::panicking::rust_panic_with_hook::h6ba758b609145e87
   7:     0x5628a4f82fea - std::panicking::begin_panic_handler::{{closure}}::h85a29a02f80cdf85
   8:     0x5628a4f81d29 - std::sys::backtrace::__rust_end_short_backtrace::hef50a48c415098fc
   9:     0x5628a4f82c7d - rust_begin_unwind
  10:     0x5628a4ce7660 - core::panicking::panic_fmt::h838eafa88a11694f
  11:     0x5628a4ce7a26 - core::result::unwrap_failed::hcfae8ee3d5612672
  12:     0x5628a4d8667c - xwayland_satellite::server::ServerState<C>::handle_clientside_events::h6f20475934128b89
  13:     0x5628a4d81b5c - xwayland_satellite::server::ServerState<C>::run::h629bfd3558a2e891
  14:     0x5628a4d926fa - xwayland_satellite::xstate::XState::handle_events::h3607e79eea057344
  15:     0x5628a4d3686c - xwayland_satellite::main::h38d26d764cea7adb
  16:     0x5628a4d48f24 - xwayland_satellite::main::hb9185f31458067f0
  17:     0x5628a4d380c3 - std::sys::backtrace::__rust_begin_short_backtrace::h6b1d19ae0a78930c
  18:     0x5628a4d5da69 - std::rt::lang_start::{{closure}}::hd0f0ea4247fa76e4
  19:     0x5628a4f79050 - std::rt::lang_start_internal::h8e3040bba25a4ac6
  20:     0x5628a4d48ff5 - main
  21:     0x7ff9f0166248 - __libc_start_call_main
  22:     0x7ff9f016630b - __libc_start_main@GLIBC_2.2.5
  23:     0x5628a4ce7db5 - _start
  24:                0x0 - <unknown>
```
This does not happen on `main`.

**Comment by merrkry** [comment]
After some use I found xwayland occasionally crashes.

[full log of xwayland-satellite from start to crash when I launched Steam](https://github.com/user-attachments/files/19719263/log.txt)

**Comment by zerodegress** [comment]
> When running TeamSpeak 6 on the scaling branch, I get the following error:在 scaling 分支上运行 TeamSpeak 6 时，我收到以下错误：
> 
> ```
> Protocol error 0 on object wp_viewport@32: negative or zero values in width or height
> 
> thread 'main' panicked at src/server/mod.rs:1067:14:
> Failed flushing clientside events: Protocol(ProtocolError { code: 0, object_id: 32, object_interface: "wp_viewport", message: "negative or zero values in width or height" })
> stack backtrace:
>    0:     0x5628a4f81830 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h935e271cc5fb90ba
>    1:     0x5628a4fa7873 - core::fmt::write::he4ddb9182edc60d6
>    2:     0x5628a4f7e743 - std::io::Write::write_fmt::hb836ec59165d98b5
>    3:     0x5628a4f81682 - std::sys::backtrace::BacktraceLock::print::h7920c6a0f5f13d53
>    4:     0x5628a4f828a4 - std::panicking::default_hook::{{closure}}::hcae04ba448f5a90b
>    5:     0x5628a4f82714 - std::panicking::default_hook::h82731dcf856564a7
>    6:     0x5628a4f83242 - std::panicking::rust_panic_with_hook::h6ba758b609145e87
>    7:     0x5628a4f82fea - std::panicking::begin_panic_handler::{{closure}}::h85a29a02f80cdf85
>    8:     0x5628a4f81d29 - std::sys::backtrace::__rust_end_short_backtrace::hef50a48c415098fc
>    9:     0x5628a4f82c7d - rust_begin_unwind
>   10:     0x5628a4ce7660 - core::panicking::panic_fmt::h838eafa88a11694f
>   11:     0x5628a4ce7a26 - core::result::unwrap_failed::hcfae8ee3d5612672
>   12:     0x5628a4d8667c - xwayland_satellite::server::ServerState<C>::handle_clientside_events::h6f20475934128b89
>   13:     0x5628a4d81b5c - xwayland_satellite::server::ServerState<C>::run::h629bfd3558a2e891
>   14:     0x5628a4d926fa - xwayland_satellite::xstate::XState::handle_events::h3607e79eea057344
>   15:     0x5628a4d3686c - xwayland_satellite::main::h38d26d764cea7adb
>   16:     0x5628a4d48f24 - xwayland_satellite::main::hb9185f31458067f0
>   17:     0x5628a4d380c3 - std::sys::backtrace::__rust_begin_short_backtrace::h6b1d19ae0a78930c
>   18:     0x5628a4d5da69 - std::rt::lang_start::{{closure}}::hd0f0ea4247fa76e4
>   19:     0x5628a4f79050 - std::rt::lang_start_internal::h8e3040bba25a4ac6
>   20:     0x5628a4d48ff5 - main
>   21:     0x7ff9f0166248 - __libc_start_call_main
>   22:     0x7ff9f016630b - __libc_start_main@GLIBC_2.2.5
>   23:     0x5628a4ce7db5 - _start
>   24:                0x0 - <unknown>
> ```
> 
> This does not happen on `main`.

```
 2025-04-12T12:01:27.129Z WARN  xwayland_satellite::server > No last focused toplevel, cannot focus window Window { res_id: 6291465 }
 2025-04-12T12:01:27.132Z WARN  xwayland_satellite::server > No last focused toplevel, cannot focus window Window { res_id: 6291466 }
 2025-04-12T12:01:27.141Z WARN  xwayland_satellite::server > No last focused toplevel, cannot focus window Window { res_id: 18874373 }
 2025-04-12T12:01:27.157Z WARN  xwayland_satellite::server > Non popup (Some(Toplevel(Some(ToplevelData { toplevel: XdgToplevel { id: ObjectId(xdg_toplevel@36, 36), version: 6, data: Some(ObjectData { .. }), backend: WeakBackend { inner: WeakInnerBackend { state: (Weak) } } }, xdg: XdgSurfaceData { surface: XdgSurface { id: ObjectId(xdg_surface@35, 35), version: 6, data: Some(ObjectData { .. }), backend: WeakBackend { inner: WeakInnerBackend { state: (Weak) } } }, configured: true, pending: None }, fullscreen: false, decoration: Some(ZxdgToplevelDecorationV1 { id: ObjectId(zxdg_toplevel_decoration_v1@37, 37), version: 1, data: Some(ObjectData { .. }), backend: WeakBackend { inner: WeakInnerBackend { state: (Weak) } } }) })))) being reconfigured, behavior may be off.
 2025-04-12T12:01:27.174Z WARN  xwayland_satellite::server > Tried to set window without surface fullscreen: Window { res_id: 18874373 }
 2025-04-12T12:01:27.174Z WARN  xwayland_satellite::server > Tried to set window without surface fullscreen: Window { res_id: 18874373 }
 2025-04-12T12:01:27.246Z WARN  xwayland_satellite::server > Non popup (Some(Toplevel(Some(ToplevelData { toplevel: XdgToplevel { id: ObjectId(xdg_toplevel@47, 54), version: 6, data: Some(ObjectData { .. }), backend: WeakBackend { inner: WeakInnerBackend { state: (Weak) } } }, xdg: XdgSurfaceData { surface: XdgSurface { id: ObjectId(xdg_surface@46, 53), version: 6, data: Some(ObjectData { .. }), backend: WeakBackend { inner: WeakInnerBackend { state: (Weak) } } }, configured: true, pending: None }, fullscreen: false, decoration: Some(ZxdgToplevelDecorationV1 { id: ObjectId(zxdg_toplevel_decoration_v1@48, 55), version: 1, data: Some(ObjectData { .. }), backend: WeakBackend { inner: WeakInnerBackend { state: (Weak) } } }) })))) being reconfigured, behavior may be off.
Protocol error 1 on object wp_viewport@52: Size was <= 0

thread 'main' panicked at /home/user/xwayland-satellite/src/server/mod.rs:1067:14:
Failed flushing clientside events: Protocol(ProtocolError { code: 1, object_id: 52, object_interface: "wp_viewport", message: "Size was <= 0" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

simlilar issue while running wine to play game which have trayicon and a launcher interface.
This does not happen on `main`, too.
P.S.: I am using hyprland

**Comment by Supreeeme** [comment]
@luleyleo @zerodegress Can you launch satellite with the env var `RUST_LOG=debug` and provide the log with the crash?

**Comment by zerodegress** [comment]
> [@luleyleo](https://github.com/luleyleo) [@zerodegress](https://github.com/zerodegress) Can you launch satellite with the env var `RUST_LOG=debug` and provide the log with the crash?@luleyleo 

[log.txt](https://github.com/user-attachments/files/19725648/log.txt)

> As a side note, desktop scaling should be around 1.6x (Hyprland auto-scaling)

**Comment by Supreeeme** [comment]
Ok, this crash should be fixed now.

**Comment by 9p4** [comment]
I'm running into a minor cosmetic bug where floating windows are created with the unscaled size, then resizing down to the scaled size (and thus being created not centered).

**Comment by merrkry** [comment]
Latest crash fixed the crash on my machine. Thanks!

**Comment by Supreeeme** [comment]
This has now been merged into main as the default behavior. Thanks to everyone who helped test it. 

Please open separate issues for any new bugs you find.

**Comment by YaLTeR** [comment]
The gtk4-demo (`GDK_BACKEND=x11`) popup menu freaks out a little at 1.333 scale. Some unfortunate rounding maybe?

https://github.com/user-attachments/assets/8ddd71a7-b77a-4238-a3f7-e74929b380d4

**Comment by Adept9559** [comment]
Has this been fully implemented yet? I'm using Discord on Niri which uses xwayland-satellite and I'm having some issues that I think forcing xwayland windows to scale of 1 would fix. I'm using a fractional scale for one of my windows.
