### ISSUE TITLE
crash on XIVLauncher

### ISSUE THREAD

**Issue by cptn-cosmo** [Supreeeme/xwayland-satellite#3]
When I try to run XIVLauncher I get the following output:

```
~ $ [S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API] SteamAPI_Init(): Loaded '/home/cosmo/.local/share/Steam/linux64/steamclient.so' OK.
[S_API FAIL] SteamAPI_Init() failed; create pipe failed.[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API] SteamAPI_Init(): Loaded '/home/cosmo/.local/share/Steam/linux64/steamclient.so' OK.
[S_API FAIL] SteamAPI_Init() failed; create pipe failed.Unhandled exception. Veldrid.VeldridException: Unable to create OpenGL Context: "That operation is not supported". This may indicate that the system does not support the requested OpenGL profile, version, or Swapchain format.
   at Veldrid.StartupUtilities.VeldridStartup.CreateDefaultOpenGLGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, GraphicsBackend backend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend)
   at XIVLauncher.Core.Program.Main(String[] args) in C:/goatsoft/xl/XIVLauncher.Core/Program.cs:line 258
```

**Comment by cptn-cosmo** [comment]
solved by settingElectron to use wayland mode :thinking:
