### ISSUE TITLE
crash with stacktrace

### ISSUE THREAD

**Issue by shumvgolove** [Supreeeme/xwayland-satellite#45]
Running the Helldivers 2 spawns two windows (the game window and I guess the tray icon), where quickly switching between them results in a crash:

```
 2024-07-28T20:45:15.691Z TRACE xwayland_satellite::xstate            > _NET_WM_STATE (Remove) props: Atom { res_id: 290 } Atom { res_id: 0 }
 2024-07-28T20:45:15.691Z DEBUG xwayland_satellite::server::event     > configuring toplevel 2560x1440, [4, 0, 0, 0, 2, 0, 0, 0]
 2024-07-28T20:45:15.691Z DEBUG xwayland_satellite::server::event     > configuring Window { res_id: 50331649 }: 0x0, 2560x1440
 2024-07-28T20:45:15.691Z TRACE xwayland_satellite::xstate            > reconfiguring window Window { res_id: 50331649 }
 2024-07-28T20:45:15.691Z DEBUG xwayland_satellite::server            > focusing window Window { res_id: 50331649 }
 2024-07-28T20:45:15.691Z TRACE xwayland_satellite::xstate            > x11 event: X(ClientMessage(ClientMessageEvent { response_type: 161, format: 32, sequence: 653, window: Window { res_id: 50331649 }, r#type: Atom { res_id: 248 }, data: Data32([0, 289, 0, 1, 0]) }))
 2024-07-28T20:45:15.691Z TRACE xwayland_satellite::xstate            > _NET_WM_STATE (Remove) props: Atom { res_id: 289 } Atom { res_id: 0 }
 2024-07-28T20:45:15.691Z TRACE xwayland_satellite::xstate            > x11 event: X(PropertyNotify(PropertyNotifyEvent { response_type: 28, pad: 1, sequence: 653, window: Window { res_id: 50331649 }, atom: Atom { res_id: 375 }, time: 580874, state: NewValue, pad: 3 }))
 2024-07-28T20:45:15.691Z DEBUG xwayland_satellite::xstate            > changed property "_NET_WM_BYPASS_COMPOSITOR" for Window { res_id: 50331649 }
 2024-07-28T20:45:15.691Z TRACE xwayland_satellite::xstate            > x11 event: X(ConfigureNotify(ConfigureNotifyEvent { response_type: 22, pad: 1, sequence: 654, event: Window { res_id: 1045 }, window: Window { res_id: 50331649 }, above_sibling: Window { res_id: 60817410 }, x: 0, y: 0, width: 2560, height: 1440, border_width: 0, override_redirect: false, pad: 1 }))
 2024-07-28T20:45:15.691Z TRACE xwayland_satellite::xstate            > x11 event: X(PropertyNotify(PropertyNotifyEvent { response_type: 28, pad: 1, sequence: 661, window: Window { res_id: 50331649 }, atom: Atom { res_id: 248 }, time: 580875, state: NewValue, pad: 3 }))
 2024-07-28T20:45:15.691Z DEBUG xwayland_satellite::xstate            > changed property "_NET_WM_STATE" for Window { res_id: 50331649 }
 2024-07-28T20:45:15.691Z TRACE xwayland_satellite::xstate            > x11 event: X(ConfigureNotify(ConfigureNotifyEvent { response_type: 22, pad: 1, sequence: 672, event: Window { res_id: 1045 }, window: Window { res_id: 50331649 }, above_sibling: Window { res_id: 60817410 }, x: 380, y: 0, width: 2560, height: 1440, border_width: 0, override_redirect: false, pad: 1 }))
 2024-07-28T20:45:15.691Z TRACE xwayland_satellite::xstate            > x11 event: X(ConfigureNotify(ConfigureNotifyEvent { response_type: 22, pad: 1, sequence: 679, event: Window { res_id: 1045 }, window: Window { res_id: 50331649 }, above_sibling: Window { res_id: 60817410 }, x: 0, y: 0, width: 2560, height: 1440, border_width: 0, override_redirect: false, pad: 1 }))
 2024-07-28T20:45:16.343Z TRACE xwayland_satellite::xstate            > x11 event: X(ConfigureNotify(ConfigureNotifyEvent { response_type: 22, pad: 1, sequence: 689, event: Window { res_id: 1045 }, window: Window { res_id: 60817409 }, above_sibling: Window { res_id: 27263107 }, x: 380, y: 0, width: 1800, height: 1440, border_width: 0, override_redirect: true, pad: 1 }))
 2024-07-28T20:45:16.343Z TRACE xwayland_satellite::xstate            > x11 event: X(MapNotify(MapNotifyEvent { response_type: 19, pad: 1, sequence: 689, event: Window { res_id: 1045 }, window: Window { res_id: 60817409 }, override_redirect: true, pad: 3 }))
 2024-07-28T20:45:16.343Z DEBUG xwayland_satellite::xstate            > got title: None
 2024-07-28T20:45:16.343Z DEBUG xwayland_satellite::server            > mapping Window { res_id: 60817409 }
 2024-07-28T20:45:16.369Z TRACE xwayland_satellite::xstate            > x11 event: X(ConfigureRequest(ConfigureRequestEvent { response_type: 23, stack_mode: Above, sequence: 698, parent: Window { res_id: 1045 }, window: Window { res_id: 50331649 }, sibling: Window { res_id: 0 }, x: -32000, y: -32000, width: 160, height: 31, border_width: 0, value_mask: X | Y | WIDTH | HEIGHT }))
 2024-07-28T20:45:16.369Z DEBUG xwayland_satellite::xstate            > Window { res_id: 50331649 } request: X | Y | WIDTH | HEIGHT
thread '<unnamed>' panicked at ./src/lib.rs:91:52:
called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
stack backtrace:
   0:     0x5bac110681f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1557845c8e738a27
   1:     0x5bac10f9294b - core::fmt::write::hcc4af7a39f871458
   2:     0x5bac110654f3 - std::io::Write::write_fmt::h2e58768ec339f8e4
   3:     0x5bac11067f6e - std::sys_common::backtrace::print::h3472d9e8ff95a48d
   4:     0x5bac110693fe - std::panicking::default_hook::{{closure}}::hedc6d80425a5f543
   5:     0x5bac110690e6 - std::panicking::default_hook::hfd8eb046669a0df4
   6:     0x5bac11069a0f - std::panicking::rust_panic_with_hook::h65b2a82740c1271c
   7:     0x5bac110697f4 - std::panicking::begin_panic_handler::{{closure}}::h93c97270af2611f9
   8:     0x5bac110686b9 - std::sys_common::backtrace::__rust_end_short_backtrace::h829948e6034c0cd2
   9:     0x5bac11069557 - rust_begin_unwind
  10:     0x5bac10f91243 - core::panicking::panic_fmt::hfc53808b4f190311
  11:     0x5bac10f916e6 - core::result::unwrap_failed::hccb2dcc79e29bd4a
  12:     0x5bac1116b364 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65020462f70c50e7
  13:     0x5bac11172248 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb2f115beaca3d3d4
  14:     0x5bac1106c4bb - std::sys::pal::unix::thread::Thread::new::thread_start::h116c3f3c1780c052
zsh: abort      xwayland-satellite
```

**Comment by nekopsykose** [comment]
does this happen on the latest main? there was quite a few bugfixes since the last release and no new release yet

**Comment by shumvgolove** [comment]
I'll try to reproduce from latest commit.

**Comment by Supreeeme** [comment]
Were you able to reproduce on latest?

**Comment by shumvgolove** [comment]
Compiled from https://github.com/Supreeeme/xwayland-satellite/commit/95afa163a60167cd97bf6afa870bc117a1be3d03 commit, can reproduce when somewhat quickly resizing the Steam window:

https://github.com/user-attachments/assets/43f6fde0-4c5d-417a-97fe-66a31ba75c82

Logs:
```
thread 'main' panicked at src/server/mod.rs:826:39:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: xwayland_satellite::server::ServerState<C>::run
   4: xwayland_satellite::xstate::XState::handle_events
   5: xwayland_satellite::main
   6: xwayland_satellite::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I assume it's a `Xwayland` crash, not necessarily `xwayland-satellite`?

**Comment by Supreeeme** [comment]
Hard to tell from just that, could you give the whole log? Also, what compositor is that?

**Comment by shumvgolove** [comment]
Here's the full log: [xwayland-satellite.log](https://github.com/user-attachments/files/16553748/xwayland-satellite.log)

Compositor is niri.

**Comment by Supreeeme** [comment]
You're resizing the window via the little thing on the Steam window? I'm curious as to why that is even working, because as far as I know it shouldn't...

**Comment by Supreeeme** [comment]
Reopen if this is still seen.

**Comment by shumvgolove** [comment]
Yeah, can't reproduce with latest commit.
