### ISSUE TITLE
xwayland-satellite panickes from app

### ISSUE THREAD

**Issue by Crdr0122** [Supreeeme/xwayland-satellite#71]
Trying to launch wechat through satellite leads to it panicking. Wechat first has a login window, then after you login the window closes and the main chat window pops up. Xwayland-satellite crashes when the main chat window is opened, it shows for a moment and then it dies. 
Wechat shows those messages 

```
X connection to :3 broken (explicit kill or server shutdown).
[1106/193313.645230:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[1106/193313.646083:ERROR:exception_handler_server.cc(144)] tgkill: No such process (3)
```

xwayland-satellite ran with `RUST_LOG=debug` shows these 

```
 2024-11-06T11:32:44.924Z DEBUG xwayland_satellite::server::event > moving wl_output@12[0] to 0x0
 2024-11-06T11:32:44.924Z DEBUG xwayland_satellite::server::event > moving zxdg_output_v1@13[0] to 0x0
 2024-11-06T11:32:45.014Z DEBUG xwayland_satellite::server::dispatch > new surface with key ObjectKey(6v1) (Some(19))
 2024-11-06T11:32:45.021Z INFO  xwayland_satellite                   > Connected to Xwayland on :3
 2024-11-06T11:32:45.021Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 41, parent: Window { res_id: 1047 }, window: Window { res_id: 2097157 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:32:45.030Z INFO  xwayland_process                     > The XKEYBOARD keymap compiler (xkbcomp) reports:
 2024-11-06T11:32:45.030Z INFO  xwayland_process                     > > Warning:          Unsupported maximum keycode 708, clipping.
 2024-11-06T11:32:45.030Z INFO  xwayland_process                     > >                   X11 cannot support keycodes above 255.
 2024-11-06T11:32:45.031Z INFO  xwayland_process                     > > Warning:          Could not resolve keysym XF86KbdInputAssistPrevgrou
 2024-11-06T11:32:45.031Z INFO  xwayland_process                     > > Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
 2024-11-06T11:32:45.031Z INFO  xwayland_process                     > Errors from xkbcomp are not fatal to the X server
 2024-11-06T11:32:59.785Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 55, parent: Window { res_id: 1047 }, window: Window { res_id: 4194308 }, x: 0, y: 0, width: 3, height: 3, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:32:59.829Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 55, parent: Window { res_id: 1047 }, window: Window { res_id: 4194310 }, x: 0, y: 0, width: 640, height: 480, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:32:59.829Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 55, parent: Window { res_id: 1047 }, window: Window { res_id: 4194312 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:32:59.905Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 55, parent: Window { res_id: 1047 }, window: Window { res_id: 6291456 }, x: -100, y: -100, width: 10, height: 10, border_width: 0, override_redirect: true, pad: 1 }
 2024-11-06T11:32:59.905Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 55, parent: Window { res_id: 1047 }, window: Window { res_id: 6291458 }, x: -10000, y: -10000, width: 10, height: 10, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:32:59.905Z DEBUG xwayland_satellite::xstate           > Window { res_id: 6291458 } request: X | Y | WIDTH | HEIGHT
 2024-11-06T11:32:59.905Z DEBUG xwayland_satellite::server           > Reconfiguring WindowData { window: Window { res_id: 6291458 }, surface_serial: None, surface_key: None, mapped: false, attrs: WindowAttributes { override_redirect: false, popup_for: None, dims: WindowDims { x: -10000, y: -10000, width: 10, height: 10 }, size_hints: None, title: None, class: None, group: None }, output_offset: WindowOutputOffset { x: 0, y: 0 }, output_key: None } WindowDims { x: -200, y: -200, width: 20, height: 20 }
 2024-11-06T11:32:59.912Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 4194310 }
 2024-11-06T11:32:59.912Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 57, parent: Window { res_id: 1047 }, window: Window { res_id: 4194313 }, x: 0, y: 0, width: 640, height: 480, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:32:59.922Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 4194313 }
 2024-11-06T11:32:59.922Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 57, parent: Window { res_id: 1047 }, window: Window { res_id: 4194315 }, x: 1140, y: 609, width: 280, height: 380, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:32:59.936Z DEBUG xwayland_satellite::xstate           > requested to map Window { res_id: 4194315 }
 2024-11-06T11:32:59.937Z DEBUG xwayland_satellite::xstate           > Window { res_id: 4194315 } geometry: GetGeometryReply { response_type: 1, depth: 24, sequence: 62, length: 0, root: Window { res_id: 1047 }, x: 1140, y: 609, width: 280, height: 380, border_width: 0, pad: 2 }
 2024-11-06T11:32:59.937Z DEBUG xwayland_satellite::server           > setting Window { res_id: 4194315 } hints WmNormalHints { min_size: Some(WinSize { width: 280, height: 380 }), max_size: Some(WinSize { width: 280, height: 380 }) }
 2024-11-06T11:32:59.937Z DEBUG xwayland_satellite::server           > mapping Window { res_id: 4194315 }
 2024-11-06T11:32:59.937Z DEBUG xwayland_satellite::server::dispatch > new surface with key ObjectKey(12v1) (Some(25))
 2024-11-06T11:32:59.937Z DEBUG xwayland_satellite::server::dispatch > associate surface 25 with Window { res_id: 4194315 }
 2024-11-06T11:32:59.937Z DEBUG xwayland_satellite::server           > creating toplevel for Window { res_id: 4194315 }
 2024-11-06T11:32:59.938Z WARN  xwayland_satellite::server::event    > unhandled xdgtoplevel event: ConfigureBounds { width: 2544, height: 1554 }
 2024-11-06T11:32:59.938Z WARN  xwayland_satellite::server::event    > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
 2024-11-06T11:32:59.938Z DEBUG xwayland_satellite::server::event    > configuring toplevel 2544x1554, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0]
 2024-11-06T11:32:59.938Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 4194315 }: 0x0, 2544x1554
 2024-11-06T11:32:59.940Z DEBUG xwayland_satellite::server::event    > wl_surface@25[0] entered wl_output@12[0]
 2024-11-06T11:32:59.940Z DEBUG xwayland_satellite::server::event    > configuring toplevel 280x380, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0, 4, 0, 0, 0]
 2024-11-06T11:32:59.940Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 4194315 }: 0x0, 280x380
 2024-11-06T11:32:59.941Z DEBUG xwayland_satellite::server           > focusing window Window { res_id: 4194315 }
 2024-11-06T11:32:59.990Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 75, parent: Window { res_id: 1047 }, window: Window { res_id: 8388609 }, x: 10, y: 10, width: 10, height: 10, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:33:00.025Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 75, parent: Window { res_id: 1047 }, window: Window { res_id: 8388611 }, x: 0, y: 0, width: 200, height: 200, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:33:00.041Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 6291458 }
 2024-11-06T11:33:00.178Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 75, parent: Window { res_id: 1047 }, window: Window { res_id: 10485760 }, x: -10000, y: -10000, width: 10, height: 10, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:33:00.178Z DEBUG xwayland_satellite::xstate           > Window { res_id: 10485760 } request: X | Y | WIDTH | HEIGHT
 2024-11-06T11:33:00.178Z DEBUG xwayland_satellite::server           > Reconfiguring WindowData { window: Window { res_id: 10485760 }, surface_serial: None, surface_key: None, mapped: false, attrs: WindowAttributes { override_redirect: false, popup_for: None, dims: WindowDims { x: -10000, y: -10000, width: 10, height: 10 }, size_hints: None, title: None, class: None, group: None }, output_offset: WindowOutputOffset { x: 0, y: 0 }, output_key: None } WindowDims { x: -200, y: -200, width: 20, height: 20 }
 2024-11-06T11:33:00.182Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 10485760 }
 2024-11-06T11:33:01.654Z DEBUG xwayland_satellite::server::event    > entering surface (10403)
 2024-11-06T11:33:01.660Z DEBUG xwayland_satellite::server::event    > wl_surface@19[0] entered wl_output@12[0]
 2024-11-06T11:33:02.153Z DEBUG xwayland_satellite::xstate           > changed property "_NET_WM_USER_TIME" for Window { res_id: 4194315 }
 2024-11-06T11:33:13.195Z DEBUG xwayland_satellite::server           > unmapping Window { res_id: 4194315 }
 2024-11-06T11:33:13.196Z DEBUG xwayland_satellite::server::dispatch > deleting key: ObjectKey(12v1) (surface 25)
 2024-11-06T11:33:13.212Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 94, parent: Window { res_id: 1047 }, window: Window { res_id: 6291459 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:33:13.223Z DEBUG xwayland_satellite::xstate           > Window { res_id: 6291459 } request: X | Y | WIDTH | HEIGHT
 2024-11-06T11:33:13.223Z DEBUG xwayland_satellite::server           > Reconfiguring WindowData { window: Window { res_id: 6291459 }, surface_serial: None, surface_key: None, mapped: false, attrs: WindowAttributes { override_redirect: false, popup_for: None, dims: WindowDims { x: 0, y: 0, width: 1, height: 1 }, size_hints: None, title: None, class: None, group: None }, output_offset: WindowOutputOffset { x: 0, y: 0 }, output_key: None } WindowDims { x: 819, y: 354, width: 922, height: 892 }
 2024-11-06T11:33:13.258Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 96, parent: Window { res_id: 1047 }, window: Window { res_id: 4194322 }, x: 0, y: 0, width: 830, height: 640, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:33:13.265Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 96, parent: Window { res_id: 1047 }, window: Window { res_id: 6291460 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, override_redirect: true, pad: 1 }
 2024-11-06T11:33:13.275Z DEBUG xwayland_satellite::xstate           > Window { res_id: 6291460 } geometry: GetGeometryReply { response_type: 1, depth: 24, sequence: 99, length: 0, root: Window { res_id: 1047 }, x: 0, y: 0, width: 1, height: 1, border_width: 0, pad: 2 }
 2024-11-06T11:33:13.275Z DEBUG xwayland_satellite::server           > setting Window { res_id: 6291460 } hints WmNormalHints { min_size: None, max_size: None }
 2024-11-06T11:33:13.275Z DEBUG xwayland_satellite::server           > mapping Window { res_id: 6291460 }
 2024-11-06T11:33:13.275Z DEBUG xwayland_satellite::server::dispatch > new surface with key ObjectKey(16v3) (Some(29))
 2024-11-06T11:33:13.275Z DEBUG xwayland_satellite::server::dispatch > associate surface 29 with Window { res_id: 6291460 }
 2024-11-06T11:33:13.275Z DEBUG xwayland_satellite::server           > creating toplevel for Window { res_id: 6291460 }
 2024-11-06T11:33:13.276Z WARN  xwayland_satellite::server::event    > unhandled xdgtoplevel event: ConfigureBounds { width: 2544, height: 1554 }
 2024-11-06T11:33:13.276Z WARN  xwayland_satellite::server::event    > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
 2024-11-06T11:33:13.276Z DEBUG xwayland_satellite::server::event    > configuring toplevel 2544x1554, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0]
 2024-11-06T11:33:13.276Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 6291460 }: 0x0, 2544x1554
 2024-11-06T11:33:13.277Z DEBUG xwayland_satellite::server::event    > wl_surface@29[0] entered wl_output@12[0]
 2024-11-06T11:33:13.277Z DEBUG xwayland_satellite::server::event    > configuring toplevel 2544x1554, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0, 4, 0, 0, 0]
 2024-11-06T11:33:13.277Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 6291460 }: 0x0, 2544x1554
 2024-11-06T11:33:13.278Z DEBUG xwayland_satellite::server           > focusing window Window { res_id: 6291460 }
 2024-11-06T11:33:13.370Z DEBUG xwayland_satellite::xstate           > changed property "_VARIABLE_REFRESH" for Window { res_id: 6291460 }
 2024-11-06T11:33:13.426Z DEBUG xwayland_satellite::xstate           > Window { res_id: 4194322 } request: X | Y | WIDTH | HEIGHT
 2024-11-06T11:33:13.426Z DEBUG xwayland_satellite::xstate           > requested to map Window { res_id: 4194322 }
 2024-11-06T11:33:13.427Z DEBUG xwayland_satellite::server           > Reconfiguring WindowData { window: Window { res_id: 4194322 }, surface_serial: None, surface_key: None, mapped: false, attrs: WindowAttributes { override_redirect: false, popup_for: None, dims: WindowDims { x: 0, y: 0, width: 830, height: 640 }, size_hints: None, title: None, class: None, group: None }, output_offset: WindowOutputOffset { x: 0, y: 0 }, output_key: None } WindowDims { x: 789, y: 444, width: 980, height: 710 }
 2024-11-06T11:33:13.427Z DEBUG xwayland_satellite::xstate           > Window { res_id: 4194322 } geometry: GetGeometryReply { response_type: 1, depth: 24, sequence: 120, length: 0, root: Window { res_id: 1047 }, x: 789, y: 444, width: 980, height: 710, border_width: 0, pad: 2 }
 2024-11-06T11:33:13.427Z DEBUG xwayland_satellite::server           > setting Window { res_id: 4194322 } hints WmNormalHints { min_size: Some(WinSize { width: 692, height: 640 }), max_size: Some(WinSize { width: 2560, height: 1600 }) }
 2024-11-06T11:33:13.427Z DEBUG xwayland_satellite::server           > mapping Window { res_id: 4194322 }
 2024-11-06T11:33:13.427Z DEBUG xwayland_satellite::server::dispatch > new surface with key ObjectKey(17v1) (Some(28))
 2024-11-06T11:33:13.427Z DEBUG xwayland_satellite::server::dispatch > associate surface 28 with Window { res_id: 4194322 }
 2024-11-06T11:33:13.427Z DEBUG xwayland_satellite::server           > creating toplevel for Window { res_id: 4194322 }
 2024-11-06T11:33:13.427Z WARN  xwayland_satellite::server::event    > unhandled xdgtoplevel event: ConfigureBounds { width: 2544, height: 1554 }
 2024-11-06T11:33:13.427Z WARN  xwayland_satellite::server::event    > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
 2024-11-06T11:33:13.428Z DEBUG xwayland_satellite::server::event    > configuring toplevel 2544x1554, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0]
 2024-11-06T11:33:13.428Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 4194322 }: 0x0, 2544x1554
 2024-11-06T11:33:13.441Z DEBUG xwayland_satellite::server::event    > wl_surface@28[0] entered wl_output@12[0]
 2024-11-06T11:33:13.441Z DEBUG xwayland_satellite::server::event    > configuring toplevel 2544x1554, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0]
 2024-11-06T11:33:13.441Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 6291460 }: 0x0, 2544x1554
 2024-11-06T11:33:13.441Z DEBUG xwayland_satellite::server::event    > configuring toplevel 2544x1554, [5, 0, 0, 0, 6, 0, 0, 0, 7, 0, 0, 0, 8, 0, 0, 0, 4, 0, 0, 0]
 2024-11-06T11:33:13.441Z DEBUG xwayland_satellite::server::event    > configuring Window { res_id: 4194322 }: 0x0, 2544x1554
 2024-11-06T11:33:13.441Z DEBUG xwayland_satellite::server           > focusing window Window { res_id: 4194322 }
 2024-11-06T11:33:13.452Z DEBUG xwayland_satellite::xstate           > destroying window Window { res_id: 4194315 }
 2024-11-06T11:33:13.473Z DEBUG xwayland_satellite::server::event    > entering surface (10460)
 2024-11-06T11:33:13.580Z DEBUG xwayland_satellite::server::event    > leaving surface (10473)
 2024-11-06T11:33:13.580Z DEBUG xwayland_satellite::server::event    > entering surface (10473)
 2024-11-06T11:33:13.604Z DEBUG xwayland_satellite::xstate           > new window: CreateNotifyEvent { response_type: 16, pad: 1, sequence: 139, parent: Window { res_id: 1047 }, window: Window { res_id: 4194330 }, x: 0, y: 0, width: 160, height: 160, border_width: 0, override_redirect: false, pad: 1 }
 2024-11-06T11:33:13.605Z DEBUG xwayland_satellite::server           > unmapping Window { res_id: 6291460 }
 2024-11-06T11:33:13.605Z DEBUG xwayland_satellite::xstate           > reparent event: ReparentNotifyEvent { response_type: 21, pad: 1, sequence: 139, event: Window { res_id: 1047 }, window: Window { res_id: 6291460 }, parent: Window { res_id: 4194330 }, x: 0, y: 0, override_redirect: true, pad: 3 }
 2024-11-06T11:33:13.605Z DEBUG xwayland_satellite::xstate           > destroying window since its parent is no longer root!
thread 'main' panicked at src/server/mod.rs:615:49:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 2024-11-06T11:33:13.606Z INFO  xwayland_process                     > (EE) failed to read Wayland events: Connection reset by peer
```

Panic happens on 0.4 as well as 0.5

**Comment by Supreeeme** [comment]
Could you get the log with `RUST_BACKTRACE=1`?

**Comment by Crdr0122** [comment]
Sure, run with `RUST_BACKTRACE=1`

```
 2024-11-08T12:41:01.486Z INFO  xwayland_process   > Errors from xkbcomp are not fatal to the X server
 2024-11-08T12:41:18.092Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: ConfigureBounds { width: 2544, height: 1554 }
 2024-11-08T12:41:18.092Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
 2024-11-08T12:41:49.795Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: ConfigureBounds { width: 2544, height: 1554 }
 2024-11-08T12:41:49.795Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
 2024-11-08T12:41:49.976Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: ConfigureBounds { width: 2544, height: 1554 }
 2024-11-08T12:41:49.976Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
thread 'main' panicked at src/server/mod.rs:615:49:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: xwayland_satellite::server::ServerState<C>::set_size_hints
   5: xwayland_satellite::xstate::XState::handle_events
   6: xwayland_satellite::main
   7: xwayland_satellite::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

run with `RUST_BACKTRACE=full`

```
 2024-11-08T12:42:27.946Z INFO  xwayland_process   > > Warning:          Could not resolve keysym XF86KbdInputAssistNextgrou
 2024-11-08T12:42:27.947Z INFO  xwayland_process   > Errors from xkbcomp are not fatal to the X server
 2024-11-08T12:42:30.404Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: ConfigureBounds { width: 2544, height: 1554 }
 2024-11-08T12:42:30.404Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
 2024-11-08T12:42:38.953Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: ConfigureBounds { width: 2544, height: 1554 }
 2024-11-08T12:42:38.953Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
 2024-11-08T12:42:39.117Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: ConfigureBounds { width: 2544, height: 1554 }
 2024-11-08T12:42:39.117Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
thread 'main' panicked at src/server/mod.rs:615:49:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x5628ab099346 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h9754a6437f1de22a
   1:     0x5628ab0eadab - core::fmt::write::hb706a393bb60a06f
   2:     0x5628ab0a0db9 - std::io::Write::write_fmt::h9b447dc5d824d0bd
   3:     0x5628ab0cb0b6 - std::panicking::default_hook::{{closure}}::h227952daede9dd84
   4:     0x5628ab0cad46 - std::panicking::default_hook::h31626ee1feb8ee2a
   5:     0x5628ab0cb611 - std::panicking::rust_panic_with_hook::h76d2aa694a00748e
   6:     0x5628ab099b13 - std::panicking::begin_panic_handler::{{closure}}::h8855a344ffa1638b
   7:     0x5628ab099559 - std::sys::backtrace::__rust_end_short_backtrace::h3110d0cbfbf26886
   8:     0x5628ab0cb1f4 - rust_begin_unwind
   9:     0x5628aae7f763 - core::panicking::panic_fmt::h3af706d0346c1c60
  10:     0x5628aae7f7ec - core::panicking::panic::h8fa9c73fac331fdb
  11:     0x5628aae7f6c9 - core::option::unwrap_failed::had2d05111e3e145c
  12:     0x5628aaef426d - xwayland_satellite::server::ServerState<C>::set_size_hints::h3512f89f4641a8e3
  13:     0x5628aaf02e18 - xwayland_satellite::xstate::XState::handle_events::h702a51a9d1c1d155
  14:     0x5628aaed5457 - xwayland_satellite::main::h5a7c6d95e01ada5b
  15:     0x5628aaec252c - xwayland_satellite::main::ha00c0d7458193ceb
  16:     0x5628aaed0a33 - std::sys::backtrace::__rust_begin_short_backtrace::ha8bb877e0304ed50
  17:     0x5628aaee2ff9 - std::rt::lang_start::{{closure}}::h34bd803035d78ff0
  18:     0x5628ab0cd985 - std::rt::lang_start_internal::h2084fce485147f46
  19:     0x5628aaec26a5 - main
  20:     0x7efcf63a727e - __libc_start_call_main
  21:     0x7efcf63a7339 - __libc_start_main_alias_2
  22:     0x5628aae7fbc5 - _start
  23:                0x0 - <unknown>

```

**Comment by Supreeeme** [comment]
Think I fixed this, can you confirm?

**Comment by Crdr0122** [comment]
Confirmed, tried it out on the latest commit and the window successfully starts.
it does still send the 6 warns so I not sure if this is anything to worry about

**Comment by Supreeeme** [comment]
As long as it's working correctly I think it's fine 👍
