### ISSUE TITLE
thread 'main' panicked at /xwayland-satellite/src/server/mod.rs:859:65:

### ISSUE THREAD

**Issue by Szybet** [Supreeeme/xwayland-satellite#81]
Logs:
```
 2024-12-07T20:12:36.943Z WARN  xwayland_satellite::xstate        > unrecognized message: Atom { res_id: 252 }
 2024-12-07T20:12:44.219Z WARN  xwayland_satellite::xstate        > unrecognized message: Atom { res_id: 252 }
 2024-12-07T21:00:45.975Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: ConfigureBounds { width: 1918, height: 1078 }
 2024-12-07T21:00:45.975Z WARN  xwayland_satellite::server::event > unhandled xdgtoplevel event: WmCapabilities { capabilities: [3, 0, 0, 0] }
 2024-12-07T21:00:45.978Z WARN  xwayland_satellite::xstate        > unrecognized message: Atom { res_id: 252 }
 2024-12-07T21:00:48.478Z WARN  xwayland_satellite::xstate        > unrecognized message: Atom { res_id: 252 }
thread 'main' panicked at /xwayland-satellite/src/server/mod.rs:859:65:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 2024-12-07T21:25:34.482Z INFO  xwayland_process                  > (EE) failed to read Wayland events: Broken pipe
```

**Comment by Supreeeme** [comment]
Could you provide a little more info? What version of satellite is this? What were you doing when this happened?

**Comment by Supreeeme** [comment]
Can you try the latest git revision?

**Comment by Supreeeme** [comment]
Reopen if you have more info.

**Comment by Szybet** [comment]
It doesn't happen anymore I think, after update
